[tool.poetry]
name = "passe_un_dessin"
version = "0.0.1"
description = "Online drawing game"
authors = ["Foucauld Degeorges <foucauld.degeorges@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11.5"
argon2-cffi = "==21.3.0"
asgiref = "==3.7.2"
dj-database-url = "==2.0.0"
django = "==4.2.3"
django-memoize = "2.3.1"
djangorestframework = "==3.14.0"
djangorestframework_simplejwt = "==5.2.2"
psycopg2-binary = "==2.9.6"
requests = "==2.31.0"
sentry-sdk = "==1.28.1"
django-eventstream = "==4.5.1"
google-auth = "==2.22.0"
django-anymail = { extras = ["mailgun"], version = "==10.0" }
django-rest-passwordreset = "==1.3.0"
django-cors-headers = "==4.2.0"

[tool.poetry.dev-dependencies]
debugpy = "==1.6.7"
flake8 = "==6.0.0"
factory-boy = "==3.3.0"
coverage = "==7.2.7"
django-debug-toolbar = "==4.1.0"
django-extensions = "==3.2.3"
isort = "==5.12.0"
black = "^19.10b0"
django-cprofile-middleware = "1.0.5"

[tool.black]
exclude = 'migrations'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
